add ReadMe
natemcmahon/Recipe-Nutri pull request #37
Opened 2023-11-06 03:40 UTC by sarahizar

2023-11-06 18:22 UTC, AnnaT7459 commented on README.md
> -# Recipe-Nutri
This is written twice if you want to delete one

2023-11-06 18:23 UTC, sarahizar commented
I can do that when i get off!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Anna Turner ***@***.***>
Sent: Monday, November 6, 2023 12:22:25 PM
To: natemcmahon/Recipe-Nutri ***@***.***>
Cc: Sara McCauley ***@***.***>; State change ***@***.***>
Subject: Re: [natemcmahon/Recipe-Nutri] add ReadMe (PR #37)


@AnnaT7459 commented on this pull request.

________________________________

In README.md<https://github.com/natemcmahon/Recipe-Nutri/pull/37#discussion_r1383781585>:

> @@ -1 +1,55 @@
-# Recipe-Nutri


This is written twice if you want to delete one

—
Reply to this email directly, view it on GitHub<https://github.com/natemcmahon/Recipe-Nutri/pull/37#pullrequestreview-1715902404>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BCLSGEGWUM3DQMEYQTZXDHDYDETGDAVCNFSM6AAAAAA663LBZOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMJVHEYDENBQGQ>.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

2023-11-06 18:26 UTC, AnnaT7459 commented on README.md
> +RecipeNutri is a web application that allows users to find and explore recipes while providing detailed nutritional information. Users can search for recipes by recipe name, view cooking instructions
In the description, we need to include the user story, but from our point of view to include our motivations and what we learned. I use the acceptance criteria to help me write this part. 

Project Requirements
You and your group will use everything you’ve learned over the past six weeks to create a real-world front-end application that you’ll be able to showcase to potential employers. The user story and acceptance criteria will depend on the project that you create, but your project must fulfil the following requirements:

Use a CSS framework other than Bootstrap.

Be deployed to GitHub Pages.

Be interactive (i.e: accept and respond to user input).

Use at least two server-side APIs.

Does not use alerts, confirms, or prompts (use modals).

Use client-side storage to store persistent data.

Be responsive.

Have a polished UI.

Have a clean repository that meets quality coding standards (file structure, naming conventions, follows best practices for class/id-naming conventions, indentation, quality comments, etc.).

Have a quality README (with unique name, description, technologies used, screenshot, and link to deployed application).

Finally, You must add your project to the portfolio that you created in Module 2. ***WE NEED TO ALL DO THIS - WHOOPS!***

2023-11-06 18:28 UTC, AnnaT7459 commented on README.md
> +
We also need to include credits for both of the APIs in APA format as well as personal communication credits for Colin, Josh, and Max for assisting us.

2023-11-06 18:29 UTC, AnnaT7459 commented on README.md
> +
Example for APIs: 
OpenWeather. (2023). 5-Day Weather Forecast API Documentation. https://openweathermap.org/forecast5

Example for personal communication: 
H. Burke (personal communication, October 15, 2023) A. Warren (personal communication, October 9, 2023) J. Diehl TA (personal communication, October 10, 2023) M. Mayfield (personal communication, October 12, 2023)

2023-11-06 18:30 UTC, AnnaT7459 requested changes
See specific comments in README

2023-11-06 23:49 UTC, AnnaT7459 approved these changes
Thanks for updating! Looks good!

2023-11-07 00:09 UTC, natemcmahon approved these changes

2023-11-07 00:09 UTC, merged